meldable region detection bug fix, check if the transformation changed the IR in tests

diff --git a/cfm_tests/cfg/nested_if_asym/Makefile b/cfm_tests/cfg/nested_if_asym/Makefile
--- a/cfm_tests/cfg/nested_if_asym/Makefile
+++ b/cfm_tests/cfg/nested_if_asym/Makefile
@@ -1,7 +1,7 @@
 include ../config.mk
 
 clang_flags=-emit-llvm -S -Xclang -disable-O0-optnone 
-opt_flags=-gvn -S 
+opt_flags=-sroa -S
 
 obj := $(patsubst %.c,%.merged.ll,$(wildcard *.c))
 inputs := $(wildcard input*.txt)
@@ -10,10 +10,20 @@ all : ${obj}
 %.merged.ll : %.c	
 	${clang} ${clang_flags} $^
 	${opt} ${opt_flags} < $(patsubst %.c,%.ll,$^) > $(patsubst %.c,%.optimized.ll,$^)
-	${opt}  ${cfmerger_flags} < $(patsubst %.c,%.optimized.ll,$^) > $@
+	${opt} ${cfmerger_flags} < $(patsubst %.c,%.optimized.ll,$^) > $@
 
 
-test : test1 test2 test3 test4
+test : is_same test1 test2 test3 
+
+is_same : ${obj}
+	@cmp -s  $(patsubst %.merged.ll,%.optimized.ll,$^) $^ ; \
+	RETVAL=$$?; \
+	if [ $$RETVAL -eq 0 ]; then \
+					echo "ERROR : transformation did NOT change source IR"; \
+	else \
+					echo "SUCCESS : transformation did change source IR"; \
+	fi
+
 
 test1  : input1.txt
 	@${lli} $(obj) < $^ > output.merged.txt
@@ -56,12 +66,19 @@ test4 : input4.txt
 	fi \
 
 
-
+test5 : input5.txt
+	@${lli} $(obj) < $^ > output.merged.txt
+	@${lli} $(patsubst %.merged.ll, %.optimized.ll, $(obj)) < $^ > output.txt
+	@diff output.merged.txt output.txt
+	@if [ $$? -eq 0 ]; then \
+		echo "PASS" ; \
+	else \
+		@echo "FAIL" ; \
+	fi \
 
 
 
 
 clean :
-	rm  -f *.ll output*.* .*.dot
-
+	rm  -f *.ll output*.*
 
diff --git a/cfm_tests/cfg/simple_if_else/Makefile b/cfm_tests/cfg/simple_if_else/Makefile
--- a/cfm_tests/cfg/simple_if_else/Makefile
+++ b/cfm_tests/cfg/simple_if_else/Makefile
@@ -9,10 +9,20 @@ all : ${obj}
 %.merged.ll : %.c	
 	${clang} ${clang_flags} $^
 	${opt} ${opt_flags} < $(patsubst %.c,%.ll,$^) > $(patsubst %.c,%.optimized.ll,$^)
-	${opt}  ${cfmerger_flags} < $(patsubst %.c,%.optimized.ll,$^) > $@
+	${opt} ${cfmerger_flags} < $(patsubst %.c,%.optimized.ll,$^) > $@
 
 
-test : test1 test2
+test : is_same test1 test2
+
+is_same : ${obj}
+	@cmp -s  $(patsubst %.merged.ll,%.optimized.ll,$^) $^ ; \
+	RETVAL=$$?; \
+	if [ $$RETVAL -eq 0 ]; then \
+					echo "ERROR : transformation did NOT change source IR"; \
+	else \
+					echo "SUCCESS : transformation did change source IR"; \
+	fi
+
 
 test1  : input1.txt
 	@${lli} $(obj) < $^ > output.merged.txt
diff --git a/cfm_tests/cfg/unify_phi/Makefile b/cfm_tests/cfg/unify_phi/Makefile
--- a/cfm_tests/cfg/unify_phi/Makefile
+++ b/cfm_tests/cfg/unify_phi/Makefile
@@ -13,7 +13,18 @@ all : ${obj}
 	${opt}  ${cfmerger_flags} < $(patsubst %.c,%.optimized.ll,$^) > $@
 
 
-test : test1 test2 test3 test4 test5 test6 test7
+test : is_same test1 test2 test3 test4 test5 test6 test7
+
+is_same : ${obj}
+	@cmp -s  $(patsubst %.merged.ll,%.optimized.ll,$^) $^ ; \
+	RETVAL=$$?; \
+	if [ $$RETVAL -eq 0 ]; then \
+					echo "ERROR : transformation did NOT change source IR"; \
+	else \
+					echo "SUCCESS : transformation did change source IR"; \
+	fi
+
+
 
 test1  : input1.txt
 	@${lli} $(obj) < $^ > output.merged.txt
